apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce  # can be used by single node only
  resources:
    requests:
      storage: 1Gi   # need 1GB of space
